package com.tt.client;

import javax.swing.*;
import java.awt.*;
import java.io.IOException;

/**
 * Created on 2019/11/25 7:20 下午
 *
 * @author lgt
 */
public class QuesGen extends javax.swing.JFrame {

    /**
     * Creates new form QuesGen
     */
    public QuesGen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        try {
            Object[][] objects=new Object[TestGui.t.dis.read()][];
            for(int i=0;i<objects.length;i++){
                objects[i]=new Object[]{TestGui.t.dis.read(),TestGui.t.dis.readUTF(),TestGui.t.dis.readUTF(),TestGui.t.dis.readUTF(),
                        TestGui.t.dis.readUTF(),TestGui.t.dis.readUTF(),TestGui.t.dis.readUTF()};
            }
            jTable1.setModel(new javax.swing.table.DefaultTableModel(
                    objects,
                    new String [] {
                            "ID", "题目内容", "A", "B", "C", "D", "答案"
                    }
            ));

        } catch (IOException e) {
            e.printStackTrace();
        }
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(400, 300, 0, 0));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("欢迎来到题库管理系统");

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton1.setText("删除题目");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    int[]select=jTable1.getSelectedRows();

                    if(select.length>0) {
                        TestGui.t.dos.write(1);
                        TestGui.t.dos.flush();
                        TestGui.t.dos.write(select.length);
                        TestGui.t.dos.flush();
                        for(int i=0;i<select.length;i++){
                            System.out.println(i);
                            TestGui.t.dos.write(Integer.parseInt(jTable1.getValueAt(select[i], 0).toString()));
                            TestGui.t.dos.flush();
                        }
                        if (!TestGui.t.dis.readBoolean()) {
                            JOptionPane.showMessageDialog(QuesGen.this, "删除失败 重新删除", "ERROR", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            JOptionPane.showMessageDialog(QuesGen.this, "删除成功，请刷新查看", "MESSAGE", JOptionPane.INFORMATION_MESSAGE);

                        }
                    }else {
                        JOptionPane.showMessageDialog(QuesGen.this, "请选择一个题", "WARNNING", JOptionPane.INFORMATION_MESSAGE);
                    }

                } catch (IOException e) {
                    e.printStackTrace();
                }

            }
        });

        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton2.setText("添加题目");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    TestGui.t.dos.write(2);
                    TestGui.t.dos.flush();
                    Point choice = new Point();
                    choice = QuesGen.this.getLocation();
                    QuesAdd quesAdd=new QuesAdd();
                    quesAdd.setVisible(true);
                    quesAdd.setLocation(choice.x+177,choice.y+28);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });

        jButton3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton3.setText("返回");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    TestGui.t.dos.write(5);
                    TestGui.t.dos.flush();
                    Point choice = new Point();
                    choice = QuesGen.this.getLocation();
                    QuesGen.this.setVisible(false);
                    TestGui.adminChoice.setVisible(true);
                    TestGui.adminChoice.setLocation(choice.x+100,choice.y+61);
                } catch (IOException e) {
                    e.printStackTrace();
                }

            }
        });


        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(15);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(40);
            jTable1.getColumnModel().getColumn(6).setMaxWidth(40);
        }

        jButton4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton4.setText("刷新");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    TestGui.t.dos.write(3);
                    TestGui.t.dos.flush();
                    Object[][] objects=new Object[TestGui.t.dis.read()][];
                    for(int i=0;i<objects.length;i++){
                        objects[i]=new Object[]{TestGui.t.dis.read(),TestGui.t.dis.readUTF(),TestGui.t.dis.readUTF(),TestGui.t.dis.readUTF(),
                                TestGui.t.dis.readUTF(),TestGui.t.dis.readUTF(),TestGui.t.dis.readUTF()};
                    }
                    jTable1.setModel(new javax.swing.table.DefaultTableModel(
                            objects,
                            new String [] {
                                    "ID", "题目内容", "A", "B", "C", "D", "答案"
                            }
                    ));

                } catch (IOException e) {
                    e.printStackTrace();
                }

            }
        });

        jButton5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton5.setText("修改题目");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    if(jTable1.getSelectedRow()>=0) {
                        TestGui.t.dos.write(4);
                        TestGui.t.dos.flush();
                        TestGui.t.dos.write(jTable1.getSelectedRow());
                        TestGui.t.dos.flush();
                        TestGui.t.dos.write(Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()));
                        TestGui.t.dos.flush();
                        Point choice = new Point();
                        choice = QuesGen.this.getLocation();
                        QuesEdit quesEdit=new QuesEdit();
                        quesEdit.setVisible(true);
                        quesEdit.setLocation(choice.x+177,choice.y+28);
                    }
                    else {
                        JOptionPane.showMessageDialog(QuesGen.this, "请选择一个题目", "WARNNING", JOptionPane.INFORMATION_MESSAGE);
                    }
                }catch (IOException e) {
                    e.printStackTrace();
                }

            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(22, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                        .addGap(7, 7, 7))
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                        .addComponent(jButton5)
                                                                        .addContainerGap()))
                                                        .addComponent(jButton1)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(288, 288, 288))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(31, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5)
                                .addGap(28, 28, 28)
                                .addComponent(jButton1)
                                .addGap(28, 28, 28)
                                .addComponent(jButton2)
                                .addGap(28, 28, 28)
                                .addComponent(jButton4)
                                .addGap(28, 28, 28)
                                .addComponent(jButton3)
                                .addGap(95, 95, 95))
        );

        pack();
    }// </editor-fold>

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuesGen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuesGen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuesGen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuesGen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuesGen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration
}
