package com.tt.client;

import javax.swing.*;
import java.awt.*;
import java.io.IOException;

/**
 * Created on 2019/11/20 5:10 下午
 *
 * @author lgt
 */

    public class StuChoice extends javax.swing.JFrame {
        /**
         * Creates new form StuChoice
         */
        public StuChoice() {
            initComponents();
        }
        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

            jPanel1 = new javax.swing.JPanel();
            jLabel1 = new javax.swing.JLabel();
            jButton1 = new javax.swing.JButton();
            jButton2 = new javax.swing.JButton();
            jButton3 = new javax.swing.JButton();
            jButton5 = new javax.swing.JButton();

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGap(0, 100, Short.MAX_VALUE)
            );
            jPanel1Layout.setVerticalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGap(0, 100, Short.MAX_VALUE)
            );

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setLocation(new java.awt.Point(400, 300));

            jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
            jLabel1.setText("欢迎来到学生管理系统");

            jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
            jButton1.setText("修改密码");
            jButton1.addActionListener(new java.awt.event.ActionListener() {

                public void actionPerformed(java.awt.event.ActionEvent evt) {

                        try {
                            jButton1ActionPerformed(evt);
                        } catch (IOException e) {
                            e.printStackTrace();
                        }
                    }

            }
            );

            jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
            jButton2.setText("开始考试");
            jButton2.addActionListener(new java.awt.event.ActionListener() {

                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    count++;
                if(count==1){
                    try {
                        jButton2ActionPerformed(evt);
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
                else {
                    JOptionPane.showMessageDialog(StuChoice.this,"已考过试了","Warning",JOptionPane.INFORMATION_MESSAGE);
                }}
            });

            jButton3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
            jButton3.setText("查询成绩");
            jButton3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    try {
                        jButton3ActionPerformed(evt);
                    } catch (IOException e) {
                        e.printStackTrace();
                    }

                }
            });

            jButton5.setText("退出");
            jButton5.addActionListener(new java.awt.event.ActionListener() {
                @Override

                public void actionPerformed(java.awt.event.ActionEvent evt) {

                    try {
                        TestGui.t.dos.write(4);
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                    System.exit(0);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addContainerGap(202, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel1)
                                                    .addGap(200, 200, 200))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(192, 192, 192))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jButton5)
                                                    .addGap(285, 285, 285))))
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(jLabel1)
                                    .addGap(42, 42, 42)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton5)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>
       private int count=0;
        private  int count1=0;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) throws IOException {
        TestGui.t.dos.write(1);
        TestGui.t.dos.flush();
        StuPwd stuPwd=new StuPwd();
if(stuPwd.getCountPwd()==0){
        Point choice=StuChoice.this.getLocation();
        stuPwd.setVisible(true);
        stuPwd.setLocation(choice);
        stuPwd.setBackground(Color.blue);
        StuChoice.this.setVisible(false);}
else {
    JOptionPane.showMessageDialog(StuChoice.this,"每次登录只能更改一次密码","Warning",
            JOptionPane.INFORMATION_MESSAGE);
}
        // TODO add your handling code here:
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) throws IOException {
        TestGui.t.dos.write(2);
        TestGui.t.dos.flush();
        if (TestGui.t.dis.read() == 0) {
            JOptionPane.showMessageDialog(StuChoice.this, "考过试了，你可以直接查看成绩了", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        } else {
            DoQues doQues = new DoQues();
            Point choice = StuChoice.this.getLocation();
            doQues.setVisible(true);
            doQues.setLocation(choice);
            doQues.setBackground(Color.BLACK);
            StuChoice.this.setVisible(false);
            // TODO add your handling code here:
        }
    }

        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) throws IOException {
            TestGui.t.dos.write(3);
            TestGui.t.dos.flush();
            if(TestGui.t.dis.read()==0){
                JOptionPane.showMessageDialog(StuChoice.this,"还没考试，没有成绩，请先考试","ERROR",JOptionPane.INFORMATION_MESSAGE);
            }else {
                stuGrade = new StuGrade();
                Point choice = StuChoice.this.getLocation();
                StuChoice.this.setVisible(false);
                stuGrade.setVisible(true);
                stuGrade.setLocation(choice);
                stuGrade.setBackground(new Color(255,231,186));
            }

            // TODO add your handling code here:
        }
    private static boolean visible(JFrame jFrame){
        boolean t=true;
        while(t){
            t=jFrame.isVisible();
            try {
                Thread.sleep(100);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
        return t;
    }
        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(StuChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(StuChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(StuChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(StuChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new StuChoice().setVisible(true);
                }
            });
        }

        // Variables declaration - do not modify
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JButton jButton5;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel jPanel1;
        private StuGrade stuGrade;
        // End of variables declaration
    }


